apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer | quote }}
{{- with .Values.ingress.annotations }}
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  tls:
    - hosts:
        - {{ .Values.ingress.prometheus.host }}
        - {{ .Values.ingress.grafana.host }}
      secretName: {{ .Values.ingress.tlsSecret }}
  rules:
    - host: {{ .Values.ingress.prometheus.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.prometheus.serviceName }}
                port:
                  number: {{ .Values.ingress.prometheus.servicePort }}
    - host: {{ .Values.ingress.grafana.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.grafana.serviceName }}
                port:
                  number: {{ .Values.ingress.grafana.servicePort }}
