{{- $tls := .Values.tls | default dict -}}
{{- $connection := .Values.connection | default dict -}}
{{- $auth := .Values.auth | default dict -}}
{{- $externalSecretRef := .Values.externalSecretRef | default "" -}}
{{- $redisUsername := get $connection "username" | default (get $auth "username" | default "default") -}}
{{- $redisPassword := get $connection "password" | default (get $auth "password" | default "") -}}
{{- $redisAclPermissions := get $connection "aclPermissions" | default (get $auth "aclPermissions" | default "+@read +@write +@keyspace +@connection") -}}
{{- if not $externalSecretRef }}
{{- $redisPassword = required "redis.connection.password must be set for the client database user when redis.externalSecretRef is empty" $redisPassword -}}
{{- end }}
{{- if or $tls.enabled $redisPassword }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.additionalConfigName" . }}
  namespace: {{ .Release.Namespace }}
data:
  redis-additional.conf: |
    {{- if $tls.enabled }}
    cluster-enabled yes
    cluster-config-file /data/nodes.conf
    cluster-node-timeout 5000
    dir /data
    port 0
    tls-port {{ .Values.cluster.port | default 6379 }}
    tls-cert-file /tls/{{ get $tls "certKey" | default "tls.crt" }}
    tls-key-file /tls/{{ get $tls "privateKeyKey" | default "tls.key" }}
    tls-ca-cert-file /tls/{{ get $tls "caKey" | default "ca.crt" }}
    tls-auth-clients no
    tls-replication yes
    tls-cluster yes
    {{- end }}
    {{- if $redisPassword }}
    requirepass {{ $redisPassword }}
    masterauth {{ $redisPassword }}
    {{- if eq $redisUsername "default" }}
    user default on >{{ $redisPassword }} ~* &* {{ $redisAclPermissions }}
    {{- else }}
    user default off
    user {{ $redisUsername }} on >{{ $redisPassword }} ~* &* {{ $redisAclPermissions }}
    {{- end }}
    {{- end }}
{{- end }}
