{{- $tls := .Values.tls | default dict -}}
{{- $cm := $tls.certManager | default dict -}}
{{- $generateCA := get $cm "generateCA" | default true -}}
{{- $ext := .Values.externalAccess | default dict -}}
{{- if $tls.enabled }}
{{- if $generateCA }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "redis.fullname" . }}-selfsigned
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "redis.caCertificateSecretName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: {{ include "redis.fullname" . }}-ca
  secretName: {{ include "redis.caCertificateSecretName" . }}
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: {{ include "redis.fullname" . }}-selfsigned
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "redis.caIssuerName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: {{ include "redis.caCertificateSecretName" . }}
---
{{- end }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "redis.tlsSecretName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "redis.tlsSecretName" . }}
  commonName: {{ include "redis.fullname" . }}-leader
  privateKey:
    algorithm: RSA
    size: 2048
  dnsNames:
  - {{ include "redis.fullname" . }}-leader
  - {{ include "redis.fullname" . }}-leader.{{ .Release.Namespace }}
  - {{ include "redis.fullname" . }}-leader.{{ .Release.Namespace }}.svc
  - {{ include "redis.fullname" . }}-leader.{{ .Release.Namespace }}.svc.cluster.local
  {{- range ($ext.publicHostnames | default list) }}
  - {{ . }}
  {{- end }}
  issuerRef:
    {{- if $generateCA }}
    name: {{ include "redis.caIssuerName" . }}
    kind: Issuer
    group: cert-manager.io
    {{- else }}
    name: {{ get ($cm.issuer | default dict) "name" }}
    kind: {{ get ($cm.issuer | default dict) "kind" | default "ClusterIssuer" }}
    group: {{ get ($cm.issuer | default dict) "group" | default "cert-manager.io" }}
    {{- end }}
{{- end }}
