apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.secretName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  root: {{ .Values.credentials.rootPassword | quote }}
  xtrabackup: {{ .Values.credentials.replicationPassword | quote }}
  monitor: {{ .Values.credentials.monitorPassword | quote }}
  clustercheck: {{ .Values.credentials.clusterCheckPassword | quote }}
  proxyadmin: {{ .Values.credentials.rootPassword | quote }}
  operator: {{ .Values.credentials.rootPassword | quote }}
  replication: {{ .Values.credentials.replicationPassword | quote }}
