apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: seang-mysql-80f66a6d-mysql
  namespace: ns-seang-03
spec:
  backup:
    image: percona/percona-xtradb-cluster-operator:1.14.0-pxc8.0-backup-pxb8.0.35
  pxc:
    configuration: |
      [mysqld]
      admin-port=33062
