apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: seang-mysql-80f66a6d
  namespace: ns-seang-03
spec:
  crVersion: 1.14.0
  secretsName: seang-mysql-80f66a6d-mysql-credentials
  backup:
    image: percona/percona-xtradb-cluster-operator:1.14.0-pxc8.0-backup-pxb8.0.35
    schedule:
      - keep: 7
        name: daily-backup
        schedule: "20 2 * * *"
        storageName: s3-storage
    storages:
      s3-storage:
        type: s3
        s3:
          bucket: ns-seang-03
          credentialsSecret: minio-credentials-seang-mysql-80f66a6d
          endpointUrl: http://my-minio-minio.storage.svc:9000
          region: us-east-1
  haproxy:
    enabled: true
    image: percona/percona-xtradb-cluster-operator:1.14.0-haproxy
    size: 2
    exposePrimary:
      enabled: true
      type: LoadBalancer
    readinessDelaySec: 120
    readinessProbes:
      timeoutSeconds: 15
    livenessDelaySec: 600
    livenessProbes:
      timeoutSeconds: 15
  pxc:
    image: percona/percona-xtradb-cluster:8.0
    size: 3
    configuration: |
      [mysqld]
      admin-port=33062
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    podDisruptionBudget:
      maxUnavailable: 1
    readinessDelaySec: 180
    readinessProbes:
      timeoutSeconds: 20
    livenessDelaySec: 1800
    livenessProbes:
      timeoutSeconds: 20
    resources:
      requests:
        cpu: 150m
        memory: 768Mi
      limits:
        cpu: 250m
        memory: 1536Mi
    sidecars:
      - name: mysqld-exporter
        image: prom/mysqld-exporter:v0.19.0
        imagePullPolicy: IfNotPresent
        args:
          - --web.listen-address=:9104
          - --mysqld.address=127.0.0.1:3306
          - --mysqld.username=monitor
        env:
          - name: MYSQLD_EXPORTER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: seang-mysql-80f66a6d-mysql-credentials
                key: monitor
        ports:
          - containerPort: 9104
            name: mysql-metrics
            protocol: TCP
    volumeSpec:
      persistentVolumeClaim:
        storageClassName: longhorn
        resources:
          requests:
            storage: 4Gi
