apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault-transit.fullname" . }}
  namespace: {{ include "vault-transit.namespace" . }}
  labels:
    app.kubernetes.io/name: vault-transit
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8200
    targetPort: http
  - name: cluster
    port: 8201
    targetPort: cluster
  selector:
    app.kubernetes.io/name: vault-transit
    app.kubernetes.io/instance: {{ .Release.Name }}
