{{- $conn := .Values.connectionHandling | default dict -}}
{{- $connEnabled := get $conn "enabled" -}}
{{- $connMode := get $conn "mode" | default "pooler" -}}
{{- if and .Values.pooler.enabled (ne $connEnabled false) (eq $connMode "pooler") }}
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: {{ include "postgresql.poolerName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  cluster:
    name: {{ include "postgresql.fullname" . }}
  type: {{ .Values.pooler.type | default "rw" }}
  instances: {{ .Values.pooler.instances | default 1 }}
  pgbouncer:
    {{- toYaml .Values.pooler.pgbouncer | nindent 4 }}
  template:
    spec:
      initContainers:
      - name: bootstrap-controller
        resources:
          {{- toYaml .Values.pooler.bootstrapControllerResources | nindent 10 }}
      containers:
      - name: pgbouncer
        resources:
          {{- toYaml .Values.pooler.resources | nindent 10 }}
  {{- if .Values.pooler.monitoring.enablePodMonitor }}
  monitoring:
    enablePodMonitor: true
  {{- end }}
{{- end }}
