apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.superuserSecretName" . }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: {{ .Values.credentials.superuser | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.appSecretName" . }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.cluster.bootstrap.owner | quote }}
  password: {{ .Values.credentials.admin | quote }}
