apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.secretName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGODB_CLUSTER_ADMIN_USER: {{ .Values.credentials.clusterAdminUser | quote }}
  MONGODB_CLUSTER_ADMIN_PASSWORD: {{ .Values.credentials.clusterAdminPassword | quote }}
  MONGODB_USER_ADMIN_USER: {{ .Values.credentials.userAdminUser | quote }}
  MONGODB_USER_ADMIN_PASSWORD: {{ .Values.credentials.userAdminPassword | quote }}
  MONGODB_CLUSTER_MONITOR_USER: {{ .Values.credentials.clusterMonitorUser | quote }}
  MONGODB_CLUSTER_MONITOR_PASSWORD: {{ .Values.credentials.clusterMonitorPassword | quote }}
  MONGODB_DATABASE_ADMIN_USER: {{ .Values.credentials.databaseAdminUser | quote }}
  MONGODB_DATABASE_ADMIN_PASSWORD: {{ .Values.credentials.databaseAdminPassword | quote }}
  MONGODB_BACKUP_USER: {{ .Values.credentials.backupUser | quote }}
  MONGODB_BACKUP_PASSWORD: {{ .Values.credentials.backupPassword | quote }}
  MONGODB_REPLICATION_KEY: {{ .Values.credentials.replicationKey | quote }}
