apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-credentials-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: minio-credentials-{{ .Release.Name }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        credentials: |
          [default]
          aws_access_key_id = {{ `{{ .AWS_ACCESS_KEY_ID }}` }}
          aws_secret_access_key = {{ `{{ .AWS_SECRET_ACCESS_KEY }}` }}
  data:
    - secretKey: root-user
      remoteRef:
        key: minio
        property: root-user
    - secretKey: root-password
      remoteRef:
        key: minio
        property: root-password
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: minio
        property: root-user
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: minio
        property: root-password
