issuer:
  enabled: false
  email: pengseangsim210@gmail.com
  name: letsencrypt-prod
  server: https://acme-v02.api.letsencrypt.org/directory
  ingressClass: nginx

ingress:
  enabled: false
  host: longhorn.autonomous-istad.com
  ingressClassName: nginx
  tls:
    enabled: false
    secretName: longhorn-tls
  serviceName: longhorn-frontend
  servicePort: 80
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
